version: 2
updates:
- package-ecosystem: pip
  directory: "/{{ cookiecutter.name }}"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
